  
#pragma config(Motor,  port1,           ArmMotor,      tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           LFMotor,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           LBMotor,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           RFMotor,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor, port5, RBMotor, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    while (true)
    {
      // This is the main execution loop for the user control program.
      // Each time through the loop your program should update motor + servo
      // values based on feedback from the joysticks.

      motor[LBMotor] = vexRT[Ch3];
      motor[LFMotor] = vexRT[Ch3];
      motor[RBMotor] = vexRT[Ch2];
      motor[RFMotor] = vexRT[Ch2];

    if(vexRT[Btn6U] == 1){
       motor[ArmMotor] = 127;
    }
    else if(vexRT[Btn6D] == 1){
       motor[ArmMotor] = -127;
    }
    else{
       motor[ArmMotor] = 0;
    }

    }
}
